[package]
name = "rust-playground"
version = "0.1.0"
authors = ["JÃ¶rn Dinkla <jdinkla@thoughtworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
